### ISSUE TITLE
Schedule Page: Error when saving with empty lookback field in selected Panel

### ISSUE THREAD

**Issue by sworup** [openmsupply/excel-report-email-scheduler#87]
## Description

- In Schedule Page
- Error when saving with empty lookback field in selected Panel

#### Error message

> ![2022-07-08 5 02 04 PM](https://user-images.githubusercontent.com/683452/177982242-67d549de-e8d1-49f8-bfc5-e8b6523baa8b.jpg)

## Cause of the error

- Had to set the lookback to string in some cases where it was previously being set as number.
- When lookback is empty 0 was being set. And when it was populated at some other point sting like `now-1d` was being set. That's why it only breaks when empty.

**Comment by sworup** [comment]
@Mai21 I have a fix for this, I am going to try it but it might need to be further tested. Locally it is working. 
Putting the code PNG as PNG has this functionality is broken already anyway 🤷🏼‍♂️.

**Comment by Mai21** [comment]
@sworup Thanks!

**Comment by sworup** [comment]
Resolved with #88
