### ISSUE TITLE
Scheduler Page: Selected Panel variables disappear on refresh

### ISSUE THREAD

**Issue by sworup** [openmsupply/excel-report-email-scheduler#89]
## Description

- For selected panel variables
- When we set panel variables they set as expected 
- When we edit the schedule the first time, the panel variables are there.
- When you refresh the page the panel variables disappear

## Video of the bug

https://user-images.githubusercontent.com/683452/177989007-3be887ba-66ba-40c8-9841-1758dac14381.mp4

**Comment by sworup** [comment]
### Possible cause

- When the schedule is loaded and the panel variables are supposed to load in default values, the do not. Have to investigate so this might not be the cause

**Comment by sworup** [comment]
@anildahalsussol discovered this bug at first.

**Comment by Mai21** [comment]
@sworup When the panel variables disappear, how is the actual data in msupply.db > ReportContent ? Was it saved or not?

**Comment by sworup** [comment]
> @sworup When the panel variables disappear, how is the actual data in msupply.db > ReportContent ? Was it saved or not?

@Mai21 this was a UI bug so data would be there in database. UI was unable to show it.

**Comment by sworup** [comment]
Merged with #93
