### ISSUE TITLE
Add day, weekday or nth day, selection option for weekly and fortnightly schedule

### ISSUE THREAD

**Issue by anildahalsussol** [openmsupply/excel-report-email-scheduler#94]
### Description

> @anildahalsussol says:
> Recently a client asked for a report to be sent every Friday. But unfortunately, we don't have options to select days.
So, it will be good to have days option for weekly and fortnight as well.

- Currently our plugin does not have day option so the email will be scheduled to fire on the day the schedule was created. e.g. if the schedule was created on Monday or 4th day of the fortnight, the the email would fire on that vary day after the weekly and fortnightly schedule. On the time of schedule creation. We cannot set another day to for the email to fire.
- This is very inconvenient, as the user or our support team would have to wait for the exact day to create the schedule. 

#### User story

- As a dashboard admin, I want to schedule a report to be sent on specific day of the week or the fortnight, so that I could create a schedule on the convenient time and have it delivered on the time I scheduled in form options.
- As a dashboard admin, I want more granular control on scheduled day of the email, so that it would more convenient for me.

**Comment by sworup** [comment]
Resolved with #95
